"""empty message

Revision ID: 16e5f000e233
Revises: 
Create Date: 2026-01-06 17:51:22.636059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e5f000e233'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('productimage_product_id_fkey'), 'productimage', type_='foreignkey')
    op.create_foreign_key(None, 'productimage', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productimage', type_='foreignkey')
    op.create_foreign_key(op.f('productimage_product_id_fkey'), 'productimage', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
